# Dependabot configuration file
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the root directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Limit the number of open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Apply security label to easily identify security updates
    labels:
      - "dependencies"
      - "security"
    # Group dependencies to reduce PR noise
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "typescript"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
