version: '3.8'

services:
  app:
    build: .
    ports:
      - "2003:3000"
    volumes:
      - ./data:/app/data
      - ./data/.ssh:/root/.ssh
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
